"""Suggested starter fields, derived from the REDHAT.xlsx and AWS.xlsx reference files.

These are SUGGESTIONS ONLY. Every brand team can keep, edit, delete, or ignore them
and add their own fields freely. Each list returns rows shaped for st.data_editor:
    {field, type, options, mandatory, conditional_rule}
"""

# ---------- Sales / Opportunity field suggestions ----------

REDHAT_OPPORTUNITY_DETAILS = [
    {"field": "End User Name",        "type": "Text",         "options": "",                                              "mandatory": True,  "conditional_rule": ""},
    {"field": "Industry Vertical",    "type": "Dropdown",     "options": "BFSI, Telco, Manufacturing, Retail, Government, IT/ITeS, Healthcare, Education, Other", "mandatory": True, "conditional_rule": ""},
    {"field": "Partner Company Name", "type": "Text",         "options": "",                                              "mandatory": True,  "conditional_rule": ""},
    {"field": "Partner Country",      "type": "Dropdown",     "options": "UAE, KSA, Qatar, Kuwait, Oman, Bahrain, India, Other", "mandatory": True, "conditional_rule": ""},
    {"field": "Partner Address",      "type": "Text",         "options": "",                                              "mandatory": True,  "conditional_rule": ""},
    {"field": "Deal Stage",           "type": "Dropdown",     "options": "Neutral, Upside, Strong Upside, Commit",        "mandatory": True,  "conditional_rule": "Sales team cannot revert from Commit without cluster sales head approval"},
    {"field": "Generated By",         "type": "Dropdown",     "options": "Partner, Redington, Brand",                     "mandatory": False, "conditional_rule": "Mandatory when stage = Strong Upside"},
    {"field": "Opportunity Segment",  "type": "Dropdown",     "options": "Telco, Enterprise, Commercial, Territory",      "mandatory": True,  "conditional_rule": ""},
    {"field": "Opportunity Type",     "type": "Multi-select", "options": "Renewal, New",                                  "mandatory": True,  "conditional_rule": ""},
]

REDHAT_CONTACT_DETAILS = [
    {"field": "Brand AM (Name/Email)", "type": "Text",     "options": "",                              "mandatory": True,  "conditional_rule": ""},
    {"field": "Redington BSM",         "type": "Dropdown", "options": "(populate from HR)",            "mandatory": True,  "conditional_rule": ""},
    {"field": "Redington PM",          "type": "Dropdown", "options": "(populate from HR)",            "mandatory": True,  "conditional_rule": ""},
    {"field": "Redington PAM",         "type": "Dropdown", "options": "(populate from HR)",            "mandatory": True,  "conditional_rule": ""},
    {"field": "Redington Pre-Sales",   "type": "Dropdown", "options": "Dharmesh, Mahdi, NA",           "mandatory": True,  "conditional_rule": ""},
    {"field": "Credit Facility",       "type": "Dropdown", "options": "OK, Not OK",                    "mandatory": False, "conditional_rule": "PAM to fill at Strong Upside (Phase 2)"},
    {"field": "Brand PAM",             "type": "Text",     "options": "",                              "mandatory": False, "conditional_rule": ""},
]

REDHAT_DEAL_DETAILS = [
    {"field": "Deal Value (ACV)",     "type": "Number",       "options": "",                                "mandatory": True,  "conditional_rule": ""},
    {"field": "Deal Value (TCV)",     "type": "Number",       "options": "",                                "mandatory": True,  "conditional_rule": ""},
    {"field": "MYP",                  "type": "Yes/No",       "options": "",                                "mandatory": True,  "conditional_rule": "If Yes, capture number of years"},
    {"field": "Services Type",        "type": "Dropdown",     "options": "T&M, Milestone, Upfront",         "mandatory": True,  "conditional_rule": "Track T&M / Milestone billing"},
    {"field": "Services Value",       "type": "Number",       "options": "",                                "mandatory": False, "conditional_rule": "Mandatory at Strong Upside"},
    {"field": "Partial Billing",      "type": "Yes/No",       "options": "",                                "mandatory": False, "conditional_rule": "Mandatory at Strong Upside"},
    {"field": "Products Detail",      "type": "Multi-select", "options": "RHEL, OpenShift, Ansible, JBoss, Services", "mandatory": True, "conditional_rule": ""},
    {"field": "Margin",               "type": "Number",       "options": "",                                "mandatory": False, "conditional_rule": ""},
    {"field": "Target Close Date",    "type": "Date",         "options": "",                                "mandatory": True,  "conditional_rule": ""},
]

# ---------- AWS-style customer + project field suggestions ----------

AWS_CUSTOMER_DETAILS = [
    {"field": "Customer Company Name", "type": "Text",     "options": "",                                  "mandatory": True,  "conditional_rule": ""},
    {"field": "Industry Vertical",     "type": "Dropdown", "options": "(industry standard)",               "mandatory": True,  "conditional_rule": ""},
    {"field": "Customer Website",      "type": "Text",     "options": "",                                  "mandatory": False, "conditional_rule": ""},
    {"field": "Country",               "type": "Dropdown", "options": "(industry standard)",               "mandatory": True,  "conditional_rule": ""},
    {"field": "Postal Code",           "type": "Text",     "options": "",                                  "mandatory": False, "conditional_rule": ""},
    {"field": "City",                  "type": "Text",     "options": "",                                  "mandatory": False, "conditional_rule": ""},
    {"field": "Address",               "type": "Text",     "options": "",                                  "mandatory": False, "conditional_rule": ""},
]

AWS_PROJECT_DETAILS = [
    {"field": "Opportunity Type",                  "type": "Dropdown",     "options": "Net New Business, Expansion, Flat Renewal", "mandatory": True,  "conditional_rule": ""},
    {"field": "Partner Opportunity ID",            "type": "Text",         "options": "",                                          "mandatory": False, "conditional_rule": ""},
    {"field": "Partner Project Title",             "type": "Text",         "options": "",                                          "mandatory": True,  "conditional_rule": ""},
    {"field": "Sales Activities",                  "type": "Multi-select", "options": "Initialized discussions with customer, Customer has shown interest, Conducted POC/Demo, In evaluation/planning, Agreed on solution, Completed action plan, Deployment, SOW Signed", "mandatory": True, "conditional_rule": ""},
    {"field": "Customer Business Problem",         "type": "Text",         "options": "",                                          "mandatory": True,  "conditional_rule": ""},
    {"field": "Solutions Offered",                 "type": "Text",         "options": "",                                          "mandatory": True,  "conditional_rule": ""},
    {"field": "AWS Products",                      "type": "Multi-select", "options": "EC2, S3, RDS, Lambda, EKS, ECS, CloudFront, Other", "mandatory": True, "conditional_rule": ""},
    {"field": "Use Case",                          "type": "Dropdown",     "options": "AI/ML & Analytics, Archiving, Big Data, Blockchain, Business Application, Container/Serverless, Databases, Edge Computing, HPC, IoT, Migration, Security & Backup, VMware, Web Development, Training, Outposts, ERP, Media, Other", "mandatory": True, "conditional_rule": ""},
    {"field": "Delivery Model",                    "type": "Multi-select", "options": "SaaS/PaaS, BYOL/AMI, Managed Services, Professional Services, Resell, Other", "mandatory": True, "conditional_rule": ""},
    {"field": "Estimated AWS Monthly Recurring Revenue", "type": "Number", "options": "",                                          "mandatory": True,  "conditional_rule": ""},
    {"field": "Target Close Date",                 "type": "Date",         "options": "",                                          "mandatory": True,  "conditional_rule": ""},
    {"field": "Opportunity Source",                "type": "Yes/No",       "options": "",                                          "mandatory": False, "conditional_rule": "If Yes, capture marketing campaign and channel"},
    {"field": "Marketing Campaign",                "type": "Text",         "options": "",                                          "mandatory": False, "conditional_rule": "Required if Opportunity Source = Yes"},
    {"field": "Marketing Channel",                 "type": "Multi-select", "options": "Event, Telemarketing, Social, Digital, Other", "mandatory": False, "conditional_rule": ""},
]

# ---------- Partner / Customer 360 (shared across all brands) ----------

PARTNER_360_FIELDS = [
    {"field": "Partner Name",          "type": "Text",     "options": "",                                                  "mandatory": True,  "conditional_rule": ""},
    {"field": "Partner Type",          "type": "Dropdown", "options": "Reseller, SI, MSP, ISV, Distributor",                "mandatory": True,  "conditional_rule": ""},
    {"field": "Partner Tier",          "type": "Dropdown", "options": "Platinum, Gold, Silver, Authorized",                 "mandatory": True,  "conditional_rule": ""},
    {"field": "Region",                "type": "Dropdown", "options": "GCC, Levant, Africa, India, SEA, Other",             "mandatory": True,  "conditional_rule": ""},
    {"field": "Country",               "type": "Dropdown", "options": "(industry standard)",                                "mandatory": True,  "conditional_rule": ""},
    {"field": "Account Manager",       "type": "Dropdown", "options": "(populate from HR)",                                 "mandatory": True,  "conditional_rule": ""},
    {"field": "Status",                "type": "Dropdown", "options": "Active, Inactive, On Hold, Terminated",              "mandatory": True,  "conditional_rule": ""},
    {"field": "Certifications Held",   "type": "Multi-select", "options": "(brand-specific list)",                           "mandatory": False, "conditional_rule": ""},
    {"field": "Rebate Eligibility",    "type": "Yes/No",   "options": "",                                                   "mandatory": False, "conditional_rule": ""},
    {"field": "MDF Status",            "type": "Yes/No",   "options": "",                                                   "mandatory": False, "conditional_rule": ""},
]

CUSTOMER_360_FIELDS = [
    {"field": "Customer Name",         "type": "Text",     "options": "",                                                  "mandatory": True,  "conditional_rule": ""},
    {"field": "Industry",              "type": "Dropdown", "options": "(industry standard)",                                "mandatory": True,  "conditional_rule": ""},
    {"field": "Customer Size",         "type": "Dropdown", "options": "SMB, Mid-Market, Enterprise, Strategic",             "mandatory": True,  "conditional_rule": ""},
    {"field": "Country",               "type": "Dropdown", "options": "(industry standard)",                                "mandatory": True,  "conditional_rule": ""},
    {"field": "Primary Partner",       "type": "Text",     "options": "",                                                   "mandatory": True,  "conditional_rule": ""},
    {"field": "Key Contacts",          "type": "Text",     "options": "",                                                   "mandatory": True,  "conditional_rule": ""},
    {"field": "Subscriptions / Licenses Owned", "type": "Text", "options": "",                                              "mandatory": False, "conditional_rule": ""},
    {"field": "Renewal Dates",         "type": "Date",     "options": "",                                                   "mandatory": False, "conditional_rule": ""},
    {"field": "Support Level",         "type": "Dropdown", "options": "Standard, Premium, Enterprise, None",                "mandatory": False, "conditional_rule": ""},
    {"field": "Parent Account",        "type": "Text",     "options": "",                                                   "mandatory": False, "conditional_rule": "Set if account is a child in a hierarchy"},
]

# ---------- Approval stages, dashboards, additional clauses (suggestions) ----------

APPROVAL_STAGE_SUGGESTIONS = [
    {"stage": "Pre-Sales review",   "approver": "Pre-Sales lead",       "trigger": "Any new opportunity",                "sla_hours": 24, "can_revert": True},
    {"stage": "BSM approval",       "approver": "Brand Solution Mgr",   "trigger": "Deal value > 50k or discount > 10%", "sla_hours": 48, "can_revert": True},
    {"stage": "PM approval",        "approver": "Product Manager",      "trigger": "Special pricing requested",          "sla_hours": 48, "can_revert": True},
    {"stage": "Finance approval",   "approver": "Finance / Credit",     "trigger": "Credit-impacted deals",               "sla_hours": 72, "can_revert": False},
    {"stage": "Business Head sign-off", "approver": "Cluster Sales Head", "trigger": "Stage = Commit, or value > 250k", "sla_hours": 72, "can_revert": False},
]

DASHBOARD_SUGGESTIONS = [
    {"dashboard": "Pipeline by stage",                    "audience": "BSM, PM, Business Head", "frequency": "Real-time"},
    {"dashboard": "Renewal vs Net New Business",           "audience": "BSM, Business Head",     "frequency": "Weekly"},
    {"dashboard": "Segment-wise revenue split",            "audience": "Business Head",          "frequency": "Weekly"},
    {"dashboard": "Redington vs Partner vs Brand-driven",  "audience": "Business Head",          "frequency": "Monthly"},
    {"dashboard": "Services vs Subscription split",        "audience": "PM, Business Head",      "frequency": "Monthly"},
    {"dashboard": "Revenue / Margin / Margin %",           "audience": "Business Head, Finance", "frequency": "Monthly"},
    {"dashboard": "Forecast vs Actual",                    "audience": "All",                    "frequency": "Weekly"},
    {"dashboard": "Top partners by revenue",               "audience": "PAM, Business Head",     "frequency": "Monthly"},
]

ADDITIONAL_CLAUSE_SUGGESTIONS = [
    "Cluster-wise visibility (each cluster sees only its own opportunities)",
    "Cluster-wise segregation of Account Managers",
    "Once moved to Strong Upside, certain fields become mandatory (MYP, Products, Subs/Services, Target Close Date)",
    "Once moved to Commit, sales team cannot revert or extend without cluster sales head approval",
    "Access to create new tags & filters restricted to cluster heads / Admin only",
    "Mandatory dedup check on Customer Name + Country before creating a new account",
    "Partner master data should be the single source of truth across all brand modules",
]
